if NAME="crawl_Timestamp" then do;
ROLE="INPUT";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="thedate" then do;
ROLE="INPUT";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="thetime" then do;
ROLE="INPUT";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="v_updownpercent" then do;
ROLE="INPUT";
LEVEL="INTERVAL";
ORDER="";
end;
drop DROP;
