if name='buyval' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='chg' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='downcnt' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='downpricesum' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='high' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='lastDone' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='low' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='open' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='sellVal' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='unchgcnt' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='upcnt' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='uppricesum' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
if name='vol' then do;
role = 'REJECTED';
comment = "PRINCOMP: PRINREJECTED";
end;
